name: "Export analytics"

on:
  push:
  # schedule:
  #   - cron:  '5 4 * * *'
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  export-analytics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run analytics export script
        env:
          GAAUTH: ${{ secrets.GAAUTH }}
        run: "python scripts/fetch.py page-traffic.dump 14"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::172025368201:role/search_analytics_github_action_role
          aws-region: eu-west-1

      - name: Copy analytics to S3
        run: |
          aws s3 cp page-traffic.dump s3://govuk-search-analytics-production/page-traffic.dump.test
