name: "Review users"

on:
  schedule:
    - cron:  '5 4 * * *'
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  review-users:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run analytics export script
        env:
          GAAUTH: ${{ secrets.GAAUTH }}
        run: "python scripts/fetch.py page-traffic.dump 14"
